---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-components
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: cert-manager-issuers
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./core/components
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secret-vars
