---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-ingress-cert
spec:
  secretName: default-ingress-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "${DATACENTER}.${ENVIRONMENT}.${DOMAIN}"
  dnsNames:
    - "${DATACENTER}.${ENVIRONMENT}.${DOMAIN}"
    - "*.${DATACENTER}.${ENVIRONMENT}.${DOMAIN}"
