---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 10m
  releaseName: ${INGRESS_CLASS:=traefik-public}
  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      version: 24.0.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  maxHistory: 3
  install:
    timeout: 10m
    replace: true
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace
  uninstall:
    keepHistory: false
  values:
    global:
      checkNewVersion: false
      sendAnonymousUsage: false
    image:
      # renovate: datasource=docker depName=traefik
      tag: "v2.10.4"
    deployment:
      kind: ${TRAEFIK_DEPLOYMENT_KIND:=Deployment}
      replicas: ${TRAEFIK_REPLICAS}
    ingressClass:
      enabled: true
      isDefaultClass: true
    ingressRoute:
      dashboard:
        enabled: true
        labels:
          kubernetes.io/ingress.class: ${INGRESS_CLASS:=traefik-public}
    logs:
      general:
        level: "INFO"
        format: json
      access:
        enabled: true
        format: json
    ports:
      traefik:
        port: 9000
      metrics:
        port: 8082
        expose: true
        exposedPort: 8082
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
    pilot:
      enabled: false
    experimental:
      plugins:
        enabled: false
    providers:
      kubernetesIngress:
        allowExternalNameServices: true
        publishedService:
          enabled: true
        ingressClass: ${INGRESS_CLASS:=traefik-public}
        allowEmptyServices: true
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        allowExternalNameServices: true
    nodeSelector: ${TRAEFIK_NODE_SELECTOR}
    tlsOptions:
      default:
        cipherSuites:
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
          - TLS_AES_256_GCM_SHA384
          - TLS_CHACHA20_POLY1305_SHA256
        curvePreferences:
          - CurveP521
          - CurveP384
        minVersion: VersionTLS12
        maxVersion: VersionTLS13
        sniStrict: true
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
  valuesFrom:
    - kind: ConfigMap
      name: override-values
      optional: true
