apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
  interval: 5m
  values:
    ui:
      color: "#${PODINFO_COLOR:=''}"
      message: "${PODINFO_MESSAGE:=''}"
    image:
      tag: 6.4.1
    ingress:
      enabled: true
      className: ${INGRESS_CLASS:=traefik-public}
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: podinfo.${DATACENTER}.${ENVIRONMENT}.${DOMAIN}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: podinfo-tls
          hosts:
            - podinfo.${DATACENTER}.${ENVIRONMENT}.${DOMAIN}
