---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/podinfo
  prune: true
  wait: true
  timeout: 5m0s
  postBuild:
    substitute:
      PODINFO_COLOR: "41b7e6"
      PODINFO_MESSAGE: "Hello K8SUG Melbourne"
