apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
  interval: 5m
  values:
    ui:
      color: "#${PODINFO_COLOR:=''}"
      message: "${PODINFO_MESSAGE:=''}"
    image:
      tag: 6.4.1
