---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  labels:
    kubernetes.io/ingress.class: ${INGRESS_CLASS:=traefik-public}
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: ${ACME_EMAIL}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: issuer-account-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-secret
              key: CF_API_TOKEN
        selector:
          dnsZones:
            - "${DOMAIN}"
            - "*.${DOMAIN}"
            - "*.${ENVIRONMENT}.${DOMAIN}"
            - "*.${DATACENTER}.${ENVIRONMENT}.${DOMAIN}"
