---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: core-components
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/podinfo
  prune: true
  wait: true
  timeout: 5m0s
  postBuild:
    substitute:
      PODINFO_COLOR: "4a5888"
      PODINFO_MESSAGE: "Hello K8SUG Melbourne - Cluster 2"
    substituteFrom:
      - kind: Secret
        name: cluster-secret-vars
