---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-controller
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: core-crds
    - name: core-helm-repos
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./core/components/cert-manager/controller
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuers
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: cert-manager-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./core/components/cert-manager/issuers
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secret-vars
