---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns-cloudflare
spec:
  releaseName: external-dns-cloudflare
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/external-dns/
      chart: external-dns
      version: 1.13.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  interval: 10m
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  maxHistory: 3
  uninstall:
    keepHistory: false
  values:
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-secret
            key: CF_API_TOKEN
    registry: txt
    txtOwnerId: "${ENVIRONMENT}-${DATACENTER}"
    provider: cloudflare
    triggerLoopOnEvent: true
    policy: sync
    domainFilters:
      - ${DOMAIN}
    sources:
      - service
      - ingress
    serviceMonitor:
      enabled: false
    resources:
      requests:
        memory: 100Mi
        cpu: 25m
      limits:
        memory: 250Mi
